[package]
name = "rapport"
version = "0.1.0"
edition = "2021"

[features]
dns = []

[dependencies]
# network
tokio = { version = "1.42.0", features = ["net", "macros", "rt-multi-thread", "fs", "io-util"] }
#crossbeam-queue = "0.3.12"
crossbeam-queue = "0.3.12"
dashmap = "6.1.0"
hickory-resolver = { version = "0.24.2", features = ["tokio-runtime"] }
tokio-metrics = "0.4.0"
futures = "0.3.31"
socket2 = "0.5.8"
lendpool = "0.1.0"
addr = { version = "*", features = ["serde"] }

# logging
env_logger = "0.11.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
opentelemetry = "0.27.1"

# cmdline parsing
clap = { version = "4.5.23", features = ["derive"] }

# cfg handling
serde = "1.0.216"
serde_derive = "1.0.216"
toml = "0.8.19"
bytes = "1.9.0"


thiserror = { version = "2.0.9" }
nestify = "0.3.3"
serde_json = "1.0.135"
#url = "2.5.4"

# rate limit
#rlimit = "0.10.2"
#libc = "0.2.168"

